config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :cars do
    resources :comments
  end
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :brand, presence: true,
                    length: { minimum: 2 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
   http_basic_authenticate_with name: "Julio", password: "Pero men", except: [:index, :show]
   
  def show
    @car = Car.find(params[:id])
  end

  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def edit
    @car = Car.find(params[:id])
  end

  def create
    @car = Car.new(car_params)

    if @car.save
      @car.save
      redirect_to @car
    else
      render 'new'
    end
  end

  def update
    @car = Car.find(params[:id])

    if @car.update(car_params)
      redirect_to @car
    else
      render 'edit'
    end
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    redirect_to cars_path
  end

  private
    def car_params
      params.require(:car).permit(:brand, :car_model)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "Julio", password: "Pero men", only: :destroy

  def create
    @car = Car.find(params[:car_id])
    @comment = @car.comments.create(comment_params)
    redirect_to car_path(@car)
  end

  def destroy
    @car = Car.find(params[:car_id])
    @comment = Car.comments.find(params[:id])
    @comment.destroy
    redirect_to car_path(@car)
  end

  private
   def comment_params
     params.require(:comment).permit(:commenter, :body)
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cars/_form.html.erb
<%= form_with model: @car, local: true do |form| %>

  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@car.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @car.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :brand %><br>
    <%= form.text_field :brand %>
  </p>

  <p>
    <%= form.label :car_model %><br>
    <%= form.text_field :car_model %>
  </p>

  <p>
    <%= form.submit %>
  </p>
  
<% end %>

app/views/cars/edit.html.erb
<h1>Editar post</h1>

<%= render 'form' %>

<%= link_to 'Atras', cars_path %>

app/views/cars/index.html.erb
<h1>Lista de Autos</h1>

<%= link_to 'Nuevo Post', new_car_path %>
<table>
  <tr>
    <th>Marca</th>
    <th>Modelo</th>
    <th></th>
  </tr>

  <% @cars.each do |car| %>
    <tr>
      <td><%= car.brand %></td>
      <td><%= car.car_model %></td>
      <td><%= link_to 'Show', car_path(car) %></td>
      <td><%= link_to 'Edit', edit_car_path(car) %></td>
      <td><%= link_to 'Destroy', car_path(car),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Atras', root_path %>

app/views/cars/new.html.erb
<h1>Nuevo auto</h1>
<%= form_with scope: :car, url: cars_path, local: true do |form| %>
  <p>
    <%= form.label :brand %><br>
    <%= form.text_field :brand %>
  </p>

  <p>
    <%= form.label :car_model %><br>
    <%= form.text_field :car_model %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Atras', cars_path %>

app/views/cars/show.html.erb
<p>
  <strong>Marca:</strong>
  <%= @car.brand %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @car.car_model %>
</p>

<h2>Comentarios</h2>
<%= render @car.comments %>

<h3>Agrega un comentario:</h3>
<%= render 'comments/form' %>
<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Atras', cars_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.car, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @car, @car.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Voiture</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Voiture</h1>
<%= link_to 'Inventario', controller: 'cars' %>